### ISSUE TITLE
Problem Statement Ready

### ISSUE THREAD

**Issue by Zhang-Zhi-ZZ** [best-zhang-zhi/CAS741Project#1]
Hi Dr.Smith,
here's the link to my problem statement.
https://github.com/best-zhang-zhi/CAS741Project/tree/master/Polynomial_Interpolation/docs/ProblemStatement

**Comment by smiths** [comment]
@best-zhang-zhi, thank you for your draft problem statement.  As given, I cannot approve this project.  I had a student do polynomial interpolation last year and it was a struggle because the problem is too easy.  (This is why I asked students to discuss their proposed projects with me in advance.)  There just isn't enough going on to identify useful variabilities with polynomial interpolation.  Fitting is a good topic, but you need to come up with something where there are more options.  An option you could consider is spline interpolation or maybe regression.

In your proposal please also emphasize the family nature of your project.  Your requirements document should be for a family of fitting/interpolating program, not just one program.   Your aim will be a library for a general purpose tool, rather than one special purpose program.

You can deduce the commonalities and variabilities by looking at existing numerical libraries for your chosen project.

You will not implement the entire library.  We will determine later what subset makes sense for the purposes of our class.

**Comment by Zhang-Zhi-ZZ** [comment]
@smiths 
Hi Dr.Smith,
Thank you for your advice. Can I change my project to double pendulum then?

**Comment by smiths** [comment]
@best-zhang-zhi, if you are interested in interpolation, you could make that work by switching to splines.  If you would prefer the double pendulum example, that is fine.

**Comment by Zhang-Zhi-ZZ** [comment]
@smiths Sure! The double pendulum seems more interesting to me :)  Can I rewrite my problem statement this weekend?

**Comment by smiths** [comment]
Sounds good @best-zhang-zhi.  Yes, please rewrite your problem statement.

**Comment by Zhang-Zhi-ZZ** [comment]
@smiths  Hi Dr.Smith, I have uploaded the new problem statement for double pendulum project, and here's the link to it:
https://github.com/best-zhang-zhi/CAS741Project/tree/master/Double%20Pendulum/docs/ProblemStatement

**Comment by smiths** [comment]
@best-zhang-zhi, I approve your new project statement.  The Lagrangian isn't the only way to derive the equations for the double pendulum.  You might find it easier to work with something less abstract.  As long as you have a good reference to follow though, you should be good either way.
