### ISSUE TITLE
IM3 equation

### ISSUE THREAD

**Issue by smiths** [best-zhang-zhi/CAS741Project#26]
The equation for IM3 needs to explain what is really happening.  The output is not the two derivatives.  The output is the angles over time.   You need to explain that you find these by solving the ODEs.  You can look at the SWHS for an example of how you write models related to ODEs in an SRS.

I'm not sure why the angles cannot be equal to zero.  Do you really need this constraint?

**Comment by Zhang-Zhi-ZZ** [comment]
I guess saying "at least one angle cannot be equal to zero" will be more accurate? Because if both angles are zero, it will not move since there's no force in x direction?

**Comment by caobo1994** [comment]
Not moving is somehow a solution, although a mundane one. I see no difficulties in removing the constraints. Sent from Mail for Windows 10 From: best-zhang-zhiSent: Tuesday, November 12, 2019 21:05To: best-zhang-zhi/CAS741ProjectCc: SubscribedSubject: Re: [best-zhang-zhi/CAS741Project] IM3 equation (#26) I guess saying "at least one angle cannot be equal to zero" will be more accurate? Because if both angles are zero, it will not move since there's no force in x direction?—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Zhang-Zhi-ZZ** [comment]
@caobo1994  This makes sense. I will modify the input data constraints! Thank you!

**Comment by Zhang-Zhi-ZZ** [comment]
The input data constraints have been updated in commit: ce8550d209999626a5a6a6baf1371e6db2e3ba2b. Thank you @caobo1994  and @smiths. I guess I will need to modify my system VnV a bit so the test cases match this new constraints.

**Comment by smiths** [comment]
@best-zhang-zhi, I'm afraid you only addressed part of my original issue.  (I should have create separate issues to make it clear that there are two issues.)  The unaddressed issue is actually the more important one.   For IM3, your output is not the second derivative of the angles.   Your output should be the angles over time.  In your description, you explain how you obtain the values of theta over time by solving the second order ODE.  As an example, the SWHS case study outputs temperature such that the given ODE is satisfied.

**Comment by Zhang-Zhi-ZZ** [comment]
Hi Dr.Smith,
The output for IM1(old IM3) is updated in commit: b8a15b0d9d3cbe271458e131a2b5947b22de5d37.
Thank you!
