### ISSUE TITLE
Terminology and Definition

### ISSUE THREAD

**Issue by deemaalomair1** [best-zhang-zhi/CAS741Project#3]
Hello Zhi Zhang,

Regarding the Terminology and Definition I think what you wrote is more likely to be symbols and their descriptions and should be moved to table of symbols. except the last terminology "Cartesian coordinate system".

**Comment by Zhang-Zhi-ZZ** [comment]
Hi Deema,
This is a good point! I removed those symbols from the terminology and definition. Thank you!

**Comment by smiths** [comment]
@best-zhang-zhi, when  you address a comment, please include the hash of the commit that closes this issue.  This provides traceability, and lets someone else verify your work, if that is every necessary.  Also, you can close an issue, once it has been closed.

**Comment by smiths** [comment]
@best-zhang-zhi, you should address my comment above about including the commit hash and closing this issue.  If you do not know how to do this, you can ask a colleague, or talk to me after class.  You want to get in the habit of taking care of these quickly, so that it does not become overwhelming later.

**Comment by best-zhang-zhi** [comment]
Hi,
This problem is fixed in commit: 
=[https://github.com/best-zhang-zhi/CAS741Project/commit/b5542c013f2acc3509f70e2eab70fce4fee021d9](url)

**Comment by Zhang-Zhi-ZZ** [comment]
Hi,
This problem has been fix in https://github.com/best-zhang-zhi/CAS741Project/commit/b5542c013f2acc3509f70e2eab70fce4fee021d9.
