### ISSUE TITLE
Please implement Module 2

### ISSUE THREAD

**Issue by Zhang-Zhi-ZZ** [best-zhang-zhi/CAS741Project#43]
Hi Bo, 
Please implement my module 2: input parameters module in either Python or Java. Thank you!

**Comment by smiths** [comment]
@caobo1994, did you implement this module?  I don't see any commits by you to the repo.  If you haven't implemented the module, can you do so soon?

**Comment by caobo1994** [comment]
@smiths, I have already done that. Please see commit https://github.com/best-zhang-zhi/CAS741Project/commit/be7f908d0c6da4960d0ff7081af09dd6f92dfacd

**Comment by smiths** [comment]
Thank you @caobo1994.  I didn't see that commit.  In the future, please include the commit hash when closing the issue, so that the traceability is built right in.

I compared your module to the implementation that @best-zhang-zhi used.  They are different.  Even the function names are different.  I haven't investigated why, but my guess is that @best-zhang-zhi made modifications to her design that changed the interface.

**Comment by caobo1994** [comment]
I had a glance at the new code, and I found out that she and I have used different formats for input files. I did not recall any file format related content in the MIS file, so I just chose one I am familiar with and informed @best-zhang-zhi about my choice. I thought she adopted mine.

**Comment by caobo1994** [comment]
> Thank you @caobo1994. I didn't see that commit. In the future, please include the commit hash when closing the issue, so that the traceability is built right in.
> 
> I compared your module to the implementation that @best-zhang-zhi used. They are different. Even the function names are different. I haven't investigated why, but my guess is that @best-zhang-zhi made modifications to her design that changed the interface.

Sorry about that. I informed @best-zhang-zhi about my implementation directly via instant messages, and I forgot to make a same one here.

**Comment by smiths** [comment]
No problem @caobo1994.
